# Generated by Django 5.2.4 on 2025-07-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/default.png', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
