# Generated by Django 5.2.4 on 2025-08-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_update_image_paths'),
    ]

    operations = [
    ]
